/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.ifba.eduardosouza.prjSpring.views;
import br.ifba.eduardosouza.prjSpring.facade.AlunoFacade;
import br.ifba.eduardosouza.prjSpring.facade.IAlunoFacade;
import br.ifba.eduardosouza.prjSpring.model.Aluno;
import br.ifba.eduardosouza.prjSpring.views.Dashboard;


import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Eduardo de Souza
 */
public class TelaCadastro extends javax.swing.JFrame {
    
    private Aluno aluno;
    private Dashboard dashboard;
    private int rowEditar;
    private boolean isOnEdit = false;
    /**
     * Creates new form TelaCadastro
     * @param dashboard
     */
    public TelaCadastro(Dashboard dashboard) {
        initComponents();
        this.dashboard = dashboard;
        jLabel1.setText("Adicionar Aluno");
    }
    //construtor para editar
    public TelaCadastro(Dashboard dashboard, int row, boolean isOnEdit) {
        initComponents();
        this.dashboard = dashboard;
        this.rowEditar = row;
        this.isOnEdit = isOnEdit;
        jLabel1.setText("Editar Aluno");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtUserName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnEnviar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add novo aluno");

        txtFirstName.setForeground(new java.awt.Color(0, 0, 0));
        txtFirstName.setText("First Name");
        txtFirstName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(234, 234, 234))); // NOI18N

        txtLastName.setForeground(new java.awt.Color(0, 0, 0));
        txtLastName.setText("Last Name");
        txtLastName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(234, 234, 234))); // NOI18N

        txtUserName.setForeground(new java.awt.Color(0, 0, 0));
        txtUserName.setText("User Name");
        txtUserName.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(234, 234, 234))); // NOI18N

        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        txtEmail.setText("Email");
        txtEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(234, 234, 234))); // NOI18N

        txtTelefone.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefone.setText("Telefone");
        txtTelefone.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(234, 234, 234))); // NOI18N

        txtMatricula.setForeground(new java.awt.Color(0, 0, 0));
        txtMatricula.setText("Matricula");
        txtMatricula.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(234, 234, 234))); // NOI18N

        btnEnviar.setBackground(new java.awt.Color(57, 196, 220));
        btnEnviar.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.setBorder(null);
        btnEnviar.setBorderPainted(false);
        btnEnviar.setFocusPainted(false);
        btnEnviar.setFocusable(false);
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnEnviar1.setBackground(new java.awt.Color(57, 196, 220));
        btnEnviar1.setFont(new java.awt.Font("Arial Black", 1, 11)); // NOI18N
        btnEnviar1.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar1.setText("Gerar Pessoa");
        btnEnviar1.setBorder(null);
        btnEnviar1.setBorderPainted(false);
        btnEnviar1.setFocusPainted(false);
        btnEnviar1.setFocusable(false);
        btnEnviar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                        .addComponent(btnEnviar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnviar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEnviar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents



    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed

        //criando um novo aluno como os dados de cadastro ou editar
        aluno = new Aluno(txtMatricula.getText(),  txtUserName.getText(), txtFirstName.getText(), txtLastName.getText(), txtEmail.getText(), txtTelefone.getText());

        //Criando um intância da minha facade
        AlunoFacade alunoFacade = new AlunoFacade();

        //verificar os campos
        boolean camposValido = alunoFacade.verificarCampos(aluno);

        //isOnEdit for false vai cadastrar
        if(isOnEdit == false){
            //Verificar o retorno se for true posso chamar meu service e salva os dados
            if(camposValido){
                //agora vou se comunicar com o facade -> service -> dao -> e salvar no database
                if(alunoFacade.cadastraNovoAluno(aluno)){
                    JOptionPane.showMessageDialog(null, "Dados salvos com sucesso");
                    //adicionar os dados na Jtable
                    inserirDadosJtable(aluno);

                }else{
                    JOptionPane.showMessageDialog(null, "Dados não salvos");
                }

            }else{ //se de false usuário não  preencheu todos os campos
                JOptionPane.showMessageDialog(null, "Erro: não pode cadastrar com algum campo em vazio");
            }

        }else{
            //Verificar se vai editar e se os campos foram preenchido
            if(isOnEdit && camposValido){
                int col = dashboard.getjTable1().getColumn("ID").getModelIndex();
                long id = (Long) dashboard.getjTable1().getValueAt(rowEditar, col);

                //se o aluno for editado como sucesso modifico a jtable com o novo dado
                if(alunoFacade.editarAluno(aluno, id)){
                    modificarTabela(aluno);
                    JOptionPane.showMessageDialog(null, "ERRO: Aluno editado como sucesso");
                }else{
                    JOptionPane.showMessageDialog(null, "ERRO: Aluno não editado");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Erro: não pode editar com algum campo em vazio");
            }
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    // modifcar a tabela com os novos dados
    public void modificarTabela(Aluno aluno){
         dashboard.getjTable1().setValueAt(aluno.getUser_name(), rowEditar, 2);
         dashboard.getjTable1().setValueAt(aluno.getFirst_name(), rowEditar, 3);
         dashboard.getjTable1().setValueAt(aluno.getLast_name(), rowEditar, 4);
         dashboard.getjTable1().setValueAt(aluno.getEmail(), rowEditar, 5);
         dashboard.getjTable1().setValueAt(aluno.getPhone(), rowEditar, 6);
         dashboard.getjTable1().setValueAt(aluno.getMatricula(), rowEditar, 7);
    }

//    Botão para gerar pessoas aleatórias -> para teste
    private void btnEnviar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviar1ActionPerformed
        AlunoFacade alunoFacade = new AlunoFacade();

        //Criando uma váriavel a para receber a pessoa gerada aleatóriamente
        Aluno a = alunoFacade.gerarAluno();
        txtMatricula.setText(a.getMatricula());
        txtUserName.setText(a.getUser_name());
        txtFirstName.setText(a.getFirst_name());
        txtLastName.setText(a.getLast_name());
        txtEmail.setText(a.getEmail());
        txtTelefone.setText(a.getPhone());
    }//GEN-LAST:event_btnEnviar1ActionPerformed

    public void inserirDadosJtable(Aluno aluno){
        //Criando um Object com os dados do usuário de cadastro
        Object[] usuarios = { "foto" ,aluno.getId(),aluno.getUser_name(),  aluno.getFirst_name(), aluno.getLast_name(),  aluno.getEmail(), aluno.getPhone(), aluno.getMatricula() };
        // adiciona o array de usuários à JTable
        DefaultTableModel dtmUsuarios = (DefaultTableModel) dashboard.getjTable1().getModel();
        dtmUsuarios.addRow(usuarios);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnEnviar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtTelefone;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
