/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.ifba.eduardosouza.prjSpring.views.render;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Eduardo de Souza
 */
public class PanelAction extends javax.swing.JPanel {

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();  
    }
    
    public void initEvent(TableActionEvent event, int row){
        btnEdit.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onEdit(row);
            }
        });
        btnRemove.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onDelete(row);
            }
        });
        btnVer.addActionListener(new ActionListener(){
            @Override
            public void actionPerformed(ActionEvent e) {
                event.onView(row);
            }
        });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        actionButton1 = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        actionButton2 = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        actionButton3 = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        actionButton4 = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        actionButton5 = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        actionButton6 = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        actionButton7 = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        actionButton8 = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        actionButton9 = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        actionButton10 = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        btnRemove = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        btnEdit = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();
        btnVer = new br.ifba.eduardosouza.prjSpring.views.render.ActionButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons/remover (1).png"))); // NOI18N
        btnRemove.setFocusPainted(false);
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons/editar.png"))); // NOI18N
        btnEdit.setFocusPainted(false);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/icons/olho.png"))); // NOI18N
        btnVer.setFocusPainted(false);
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btnVer, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRemove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton actionButton1;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton actionButton10;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton actionButton2;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton actionButton3;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton actionButton4;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton actionButton5;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton actionButton6;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton actionButton7;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton actionButton8;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton actionButton9;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton btnEdit;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton btnRemove;
    private br.ifba.eduardosouza.prjSpring.views.render.ActionButton btnVer;
    // End of variables declaration//GEN-END:variables
}
